### ISSUE TITLE
Epic: Authentication and authorization

### ISSUE THREAD

**Issue by Sirmov** [Sirmov/My-Kitchen-Back-End#1]
### Description:
The goal of this epic is to build the infrastructure need to authenticate and authorize the users of the application.

### Acceptance Criteria:
- [ ] JWT based authentication and authorization
- [ ] Refresh token
- [ ] Cookie based authentication and authorization
- [ ] Account features (email confirmation, password reset etc.)
- [ ] Roles and policies support

### Related User Stories:
- [ ] User Story (#2, #3)
